site_name: UFO Documentation
nav:
  - Home: index.md
  - Getting Started: 
    - Quick Start: getting_started/quick_start.md
    - More Guidance: getting_started/more_guidance.md
  - Project: 
      - Project Directory Structure: project/project_directory_structure.md
      - Session: project/session.md
      - Round: project/round.md
      - Agent: project/agent.md
      - Context: project/context.md
      - Automator: project/automator.md
  - Configurations: 
      - User Configuration: configurations/user_configuration.md
      - Developer Configuration: configurations/developer_configuration.md
      - Model Pricing: configurations/pricing_configuration.md
  - Advanced Usage: 
      - Reinforcing AppAgent:
        - Learning from Demonstration: advanced_usage/learning_from_demonstration.md
        - Learning from Bing Search: advanced_usage/learning_from_bing_search.md
        - Experience Learning: advanced_usage/experience_learning.md
        - Learning from Help Document: advanced_usage/learning_from_help_document.md
      - Follower Mode: advanced_usage/follower_model.md
      - Control Filtering: advanced_usage/control_filtering.md
      - Customization: advanced_usage/customization.md
  - Supported Models: 
      - OpenAI: supported_models/openai.md
      - Azure OpenAI: supported_models/azure_openai.md
      - Qwen: supported_models/qwen.md
      - Genimi: supported_models/genimi.md
      - Ollama: supported_models/ollama.md
      - Custom Model: supported_models/custom_model.md
  - Agents:
      - Agent Design:
          - Memory: agents/design/memory.md
          - Blackboard: agents/design/blackboard.md
          - State: agents/design/state.md
          - Prompter: agents/design/prompter.md
          - Processor: agents/design/processor.md
      - HostAgent: agents/host_agent.md
      - AppAgent: agents/app_agent.md
      - FollowerAgent: agents/follower_agent.md
      - EvaluationAgent: agents/evaluation.md
  - Creating Your AppAgent: 
      - Help Document Provision: creating_app_agent/help_document_provision.md
      - Demonstration Provision: creating_app_agent/demonstration_provision.md
      - Warpping App-Native API: creating_app_agent/warpping_app_native_api.md
  - Evaluation:
      - Evaluation: evaluation/evaluation.md
      - Evaluation Session: evaluation/evaluation_session.md
      - Evaluation Round: evaluation/evaluation_round.md
      - Evaluation Agent: evaluation/evaluation_agent.md
  - Prompts:
      - Basic Prompts: prompts/basic_prompts.md
      - Examples Prompts: prompts/examples_prompts.md
      - API Prompts: prompts/api_prompts.md
  - Logs: 
      - Request Logs: logs/request_logs.md
      - Step Logs: logs/step_logs.md
      - Evaluation Logs: logs/evaluation_logs.md
      - Screenshots: logs/screenshots.md
  - About:
      - Contributing: about/CONTRIBUTING.md
      - License: about/LICENSE.md
      - Disclaimer: about/DISCLAIMER.md
      - Support: about/SUPPORT.md
      - FAQ: about/faq.md

markdown_extensions:
  - pymdownx.tasklist

theme:
  name: readthedocs

# theme:
#   name: material
#   palette:
#     primary: blue
#     accent: light-blue
#   font:
#     text: Roboto
#     code: Roboto Mono

  # logo: ./assets/ufo_blue.png
  favicon: ./assets/ufo_blue.png
